add_executable(	classTemplates CPP_Sample/CPP/classTemplates.cpp	)
	add_executable(	destructor CPP_Sample/CPP/destructor.cpp 	)
	add_executable(	functionOverloading	CPP_Sample/CPP/functionOverloading.cpp	)
	add_executable(	multipleInheritance	CPP_Sample/CPP/multipleInheritance.cpp	)
	add_executable(	operatorOverloading CPP_Sample/CPP/operatorOverloading.cpp	)
	add_executable(	simpleif_else CPP_Sample/CPP/simpleif_else.cpp	)
	add_executable(	conditionalLoop CPP_Sample/CPP/conditionalLoop.cpp	)
	add_executable(	exceptionalHandling CPP_Sample/CPP/	exceptionalHandling.cpp)
	add_executable(	functionPointers CPP_Sample/CPP/functionPointers.cpp)
	add_executable(	nameSpace CPP_Sample/CPP/nameSpace.cpp	)
	add_executable(	polymorphism CPP_Sample/CPP/polymorphism.cpp	)